name: windows-build
on: [push, pull_request]
jobs:
  compile-cpp:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        cpp-version: [c++11, c++14, c++17, c++20]
    steps:
    - uses: actions/checkout@v2
    - name: Check version
      run: |
        C:\msys64\mingw64\bin\g++ --version
    - name: Replace pragma once
      run: C:\msys64\usr\bin\find "Content/" -name "*.h" -printf "%p " | C:\msys64\usr\bin\xargs python3 Scripts/ReplacePragmas.py
    - name: Compile
      run: C:\msys64\usr\bin\find "Content/" -name "*.h" -printf "%p " | C:\msys64\usr\bin\xargs Scripts/Compile.sh "C:\msys64\mingw64\bin\g++ -std=${{ matrix.cpp-version }} -Wall -Wextra -pedantic-errors -Werror -fsyntax-only"
